version: "2.2"

services:
  postgres:
    container_name: coffea-database
    image: postgres:16.0
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d/
      - ./data/postgres:/var/lib/postgresql/data

  api:
    container_name: coffea-api
    image: node:25-bullseye
    restart: always
    links:
      - postgres
    depends_on:
      - postgres
    ports:
      - "3020:3000"
    working_dir: /app
    command: npm run start:dev
    volumes:
      - "./api:/app"
      - "./data/storage:/storage"
    environment:
      DB_HOST: postgres
      DB_USERNAME: admin
      DB_NAME: ${DATABASE_NAME}
      DB_PASSWORD:  ${DATABASE_PASSWORD}

  web:
    container_name: coffea-web
    image: node:25-bullseye
    restart: always
    links:
      - api
    depends_on:
      - api
    ports:
      - "3030:3030"
    working_dir: /app
    command: npm run dev
    volumes:
      - "./web:/app"
    environment:
      PORT: 3030
